version: '3.8'
services:
  db:
    image: mysql/mysql-server:latest
    container_name: students-mysql
    restart: always
    environment:
      - MYSQL_DATABASE=students
      - MYSQL_ROOT_PASSWORD=admin
      - MYSQL_ROOT_HOST='%'  # needs to be enclosed with quotes
    expose:
      - '3306'
    ports:
      - '3306:3306'
    volumes:
      - mysql-volume:/var/lib/mysql
    networks:
      - db
    command: --default-authentication-plugin=mysql_native_password
    healthcheck:
      test: "mysqladmin ping -h localhost"
      interval: 1s
      timeout: 1s
      retries: 60
volumes:
  mysql-volume:
    driver: loca
networks:
  external-net:
    external:
      name: external-net
  db:
    driver: bridge



#     version: "3"
# services:
#   db:
#     image: mysql:5.7
#     restart: always
#     container_name: db
#     environment:
#       - MYSQL_ROOT_PASSWORD=rootpasswd
#       - MYSQL_DATABASE=phpmyadmin
#       - MYSQL_USER=user
#       - MYSQL_PASSWORD=userpasswd
#     networks:
#       - db
#     command: --default-authentication-plugin=mysql_native_password
#     healthcheck:
#       test: "mysqladmin ping -h localhost"
#       interval: 1s
#       timeout: 1s
#       retries: 60

#   phpmyadmin:
#     image: phpmyadmin/phpmyadmin:4.7
#     restart: always
#     container_name: phpmyadmin
#     ports:
#       - 8080:80
#     networks:
#       - external-net
#       - db
#     environment:
#       PMA_HOST: db
#     depends_on:
#       - db

# networks:
#   external-net:
#     external:
#       name: external-net
#   db:
#     driver: bridge